proxy_app = "tcp://127.0.0.1:26658"
moniker = "skoed-validator-7000"
fast_sync = true
db_backend = "leveldb"
db_path = "data"
log_level = "main:info,state:info,*:error"
genesis_file = "config/genesis.json"
priv_validator_file = "config/priv_validator.json"
node_key_file = "config/node_key.json"
abci = "socket"
prof_laddr = ""
filter_peers = false
[rpc]
laddr = "tcp://0.0.0.0:26657"
grpc_laddr = ""
grpc_max_open_connections = 900
unsafe = false
max_open_connections = 900
[p2p]
laddr = "tcp://0.0.0.0:26656"
upnp = false
addr_book_file = "config/addrbook.json"
addr_book_strict = true
flush_throttle_timeout = 100
max_num_peers = 50
max_packet_msg_payload_size = 1024
send_rate = 512000
recv_rate = 512000
pex = true
seed_mode = false
[mempool]
recheck = true
recheck_empty = true
broadcast = true
wal_dir = "data/mempool.wal"
size = 100000
cache_size = 100000
[consensus]
wal_file = "data/cs.wal/wal"
timeout_propose = 3000
timeout_propose_delta = 500
timeout_prevote = 1000
timeout_prevote_delta = 500
timeout_precommit = 1000
timeout_precommit_delta = 500
timeout_commit = 1000
skip_timeout_commit = false
create_empty_blocks = true
create_empty_blocks_interval = 0
peer_gossip_sleep_duration = 100
peer_query_maj23_sleep_duration = 2000
[tx_index]
indexer = "kv"
index_tags = ""
index_all_tags = false
[instrumentation]
prometheus = false
prometheus_listen_addr = ":26660"
max_open_connections = 3
